import { Match, UserProfile, UserPrediction, PastResult } from './types.ts';

export const INITIAL_FEATURED_MATCH: Match = {
  id: 'match-ger-arg-2026',
  competition: 'FIFA WORLD CUP',
  stage: 'Quarter-Final',
  homeTeam: 'Germany',
  homeFlag: '🇩🇪',
  homeCode: 'GER',
  awayTeam: 'Argentina',
  awayFlag: '🇦🇷',
  awayCode: 'ARG',
  kickoffTime: 'Today · 20:00',
  stadium: 'Lusail Stadium, Doha',
  status: 'upcoming',
  communityStats: {
    totalPredictions: 1248,
    homeWinPct: 58,
    drawPct: 21,
    awayWinPct: 21,
  },
};

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'user-1',
    name: 'Lukas M.',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    points: 47,
    predictionsCount: 12,
    exactScoresCount: 5,
    correctOutcomesCount: 5,
    incorrectCount: 2,
    accuracyPct: 83,
    rank: 1,
    isCurrentUser: false,
  },
  {
    id: 'user-2',
    name: 'Anna K.',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=100&auto=format&fit=crop&q=80',
    points: 43,
    predictionsCount: 12,
    exactScoresCount: 4,
    correctOutcomesCount: 6,
    incorrectCount: 2,
    accuracyPct: 83,
    rank: 2,
    isCurrentUser: false,
  },
  {
    id: 'user-3',
    name: 'Max S.',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    points: 41,
    predictionsCount: 11,
    exactScoresCount: 4,
    correctOutcomesCount: 5,
    incorrectCount: 2,
    accuracyPct: 82,
    rank: 3,
    isCurrentUser: false,
  },
  {
    id: 'user-4',
    name: 'Jonas R.',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
    points: 38,
    predictionsCount: 10,
    exactScoresCount: 3,
    correctOutcomesCount: 6,
    incorrectCount: 1,
    accuracyPct: 90,
    rank: 4,
    isCurrentUser: false,
  },
  {
    id: 'user-5',
    name: 'Sophie W.',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
    points: 35,
    predictionsCount: 12,
    exactScoresCount: 3,
    correctOutcomesCount: 5,
    incorrectCount: 4,
    accuracyPct: 67,
    rank: 5,
    isCurrentUser: false,
  },
  {
    id: 'user-6',
    name: 'Felix B.',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=100&auto=format&fit=crop&q=80',
    points: 34,
    predictionsCount: 10,
    exactScoresCount: 3,
    correctOutcomesCount: 4,
    incorrectCount: 3,
    accuracyPct: 70,
    rank: 6,
    isCurrentUser: false,
  },
  {
    id: 'user-7',
    name: 'Nina H.',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&auto=format&fit=crop&q=80',
    points: 32,
    predictionsCount: 9,
    exactScoresCount: 3,
    correctOutcomesCount: 3,
    incorrectCount: 3,
    accuracyPct: 67,
    rank: 7,
    isCurrentUser: false,
  },
  {
    id: 'current-user-ernest',
    name: 'Ernest Z.',
    avatar: '',
    points: 31,
    predictionsCount: 9,
    exactScoresCount: 3,
    correctOutcomesCount: 3,
    incorrectCount: 3,
    accuracyPct: 67,
    rank: 8,
    isCurrentUser: true,
  },
  {
    id: 'user-9',
    name: 'Tim B.',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=100&auto=format&fit=crop&q=80',
    points: 28,
    predictionsCount: 9,
    exactScoresCount: 2,
    correctOutcomesCount: 4,
    incorrectCount: 3,
    accuracyPct: 67,
    rank: 9,
    isCurrentUser: false,
  },
  {
    id: 'user-10',
    name: 'Mia L.',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100&auto=format&fit=crop&q=80',
    points: 25,
    predictionsCount: 8,
    exactScoresCount: 2,
    correctOutcomesCount: 3,
    incorrectCount: 3,
    accuracyPct: 63,
    rank: 10,
    isCurrentUser: false,
  },
];

export const INITIAL_SEEDED_PREDICTIONS: UserPrediction[] = [
  {
    userId: 'current-user-ernest',
    userName: 'Ernest Z.',
    matchId: 'match-ger-arg-2026',
    predictedHomeScore: 2,
    predictedAwayScore: 1,
    submittedAt: 'Today, 14:22',
    isCurrentUser: true,
  },
  {
    userId: 'user-1',
    userName: 'Lukas M.',
    matchId: 'match-ger-arg-2026',
    predictedHomeScore: 3,
    predictedAwayScore: 1,
    submittedAt: 'Today, 11:15',
  },
  {
    userId: 'user-2',
    userName: 'Anna K.',
    matchId: 'match-ger-arg-2026',
    predictedHomeScore: 1,
    predictedAwayScore: 1,
    submittedAt: 'Today, 12:04',
  },
  {
    userId: 'user-3',
    userName: 'Max S.',
    matchId: 'match-ger-arg-2026',
    predictedHomeScore: 2,
    predictedAwayScore: 1,
    submittedAt: 'Today, 13:30',
  },
  {
    userId: 'user-4',
    userName: 'Jonas R.',
    matchId: 'match-ger-arg-2026',
    predictedHomeScore: 2,
    predictedAwayScore: 0,
    submittedAt: 'Today, 09:45',
  },
  {
    userId: 'user-5',
    userName: 'Sophie W.',
    matchId: 'match-ger-arg-2026',
    predictedHomeScore: 0,
    predictedAwayScore: 2,
    submittedAt: 'Today, 15:10',
  },
  {
    userId: 'user-6',
    userName: 'Felix B.',
    matchId: 'match-ger-arg-2026',
    predictedHomeScore: 1,
    predictedAwayScore: 0,
    submittedAt: 'Today, 10:20',
  },
  {
    userId: 'user-7',
    userName: 'Nina H.',
    matchId: 'match-ger-arg-2026',
    predictedHomeScore: 1,
    predictedAwayScore: 2,
    submittedAt: 'Today, 14:05',
  },
  {
    userId: 'user-9',
    userName: 'Tim B.',
    matchId: 'match-ger-arg-2026',
    predictedHomeScore: 2,
    predictedAwayScore: 1,
    submittedAt: 'Today, 16:12',
  },
  {
    userId: 'user-10',
    userName: 'Mia L.',
    matchId: 'match-ger-arg-2026',
    predictedHomeScore: 3,
    predictedAwayScore: 2,
    submittedAt: 'Today, 16:45',
  },
  {
    userId: 'user-11',
    userName: 'David K.',
    matchId: 'match-ger-arg-2026',
    predictedHomeScore: 0,
    predictedAwayScore: 0,
    submittedAt: 'Today, 17:01',
  },
  {
    userId: 'user-12',
    userName: 'Leon S.',
    matchId: 'match-ger-arg-2026',
    predictedHomeScore: 4,
    predictedAwayScore: 1,
    submittedAt: 'Today, 17:30',
  },
];

export const INITIAL_PAST_RESULTS: PastResult[] = [
  {
    id: 'res-1',
    match: 'Germany 2 : 1 France',
    homeFlag: '🇩🇪',
    awayFlag: '🇫🇷',
    score: '2 : 1',
    stage: 'Round of 16',
    exactPredictions: 34,
    correctOutcomes: 82,
    incorrectPredictions: 41,
    userPoints: 5,
    userCategory: 'exact',
  },
  {
    id: 'res-2',
    match: 'Brazil 1 : 1 Spain',
    homeFlag: '🇧🇷',
    awayFlag: '🇪🇸',
    score: '1 : 1',
    stage: 'Round of 16',
    exactPredictions: 48,
    correctOutcomes: 65,
    incorrectPredictions: 52,
    userPoints: 2,
    userCategory: 'outcome',
  },
  {
    id: 'res-3',
    match: 'England 3 : 0 Senegal',
    homeFlag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    awayFlag: '🇸🇳',
    score: '3 : 0',
    stage: 'Round of 16',
    exactPredictions: 61,
    correctOutcomes: 77,
    incorrectPredictions: 22,
    userPoints: 2,
    userCategory: 'outcome',
  },
];
